### ISSUE TITLE
release - fix build version bug

### ISSUE THREAD

**Issue by Serena1993** [eleme/bigkeeper#46]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [README.md](https://github.com/BigKeeper/big-keeper/blob/master/README.md), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/BigKeeper/big-keeper/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by sfmDev** [comment]
We decided not to do this feature in this release after discussion, the middle-version & last_version dont more than 10; eg: x.9.x is correct, x.10.x will have an error.

**Comment by sfmDev** [comment]
We decided not to do this feature in this release after discussion, the middle-version & last_version dont more than 10; eg: x.9.x is correct, x.10.x will have an error.
